AWSTemplateFormatVersion: "2010-09-09"
Description: Batch data analysis

Parameters:

  DatalakeStack:
    Type: String
    Description: Datalake buckets stack name
  CuratedDatabaseName:
    Type: String
    Description: Name of the curated database
    AllowedPattern: "[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*"
  StagingDatabaseName:
    Type: String
    Description: Name of the staging database
    AllowedPattern: "[\u0020-\uD7FF\uE000-\uFFFD\uD800\uDC00-\uDBFF\uDFFF\t]*"
  OscCuratedPrefix:
    Type: String
    Description: S3 Prefix of the Open Street Map change source in curated bucket.
  OscStagingPrefix:
    Type: String
    Description: S3 Prefix of the Open Street Map change source in staging bucket.
  KmsKeyArn:
    Type: String
    Description: KMS key ARN to encrypt data on rest.

Resources:
  CuratedDatabase:
    Type: "AWS::Glue::Database"
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Ref CuratedDatabaseName
        Description: !Sub "${CuratedDatabaseName} in Stack ${AWS::StackName}"

  StagingDatabase:
    Type: "AWS::Glue::Database"
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseInput:
        Name: !Ref StagingDatabaseName
        Description: !Sub "${StagingDatabaseName} in Stack ${AWS::StackName}"

  AllowUseKmsKeyPolicy:
    Type: "AWS::IAM::ManagedPolicy"
    Properties:
      Description: "Policy for accessing Kms Key"
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowUseKey
            Effect: Allow
            Action:
              - kms:Encrypt
              - kms:Decrypt
              - kms:ReEncrypt*
              - kms:GenerateDataKey*
              - kms:DescribeKey
            Resource:
              - !Ref KmsKeyArn
          - Sid: AllowAttachmentPersistentResources
            Effect: Allow
            Action:
              - kms:CreateGrant
              - kms:ListGrants
              - kms:RevokeGrant
            Resource:
              - !Ref KmsKeyArn
            Condition:
              Bool:
                kms:GrantIsForAWSResource: "true"

  OscCrawlerRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
             Service: "glue.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
        - "arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole"
        - !Ref AllowUseKmsKeyPolicy

  OscCuratedCrawler:
    Type: "AWS::Glue::Crawler"
    DependsOn: CuratedDatabase
    Properties:
      DatabaseName: !Ref CuratedDatabase
      Role: !GetAtt OscCrawlerRole.Arn
      TablePrefix: 'osc/'
      Targets:
        S3Targets:
          - Path: !Sub
            - "s3://${CuratedBucket}/${OscCuratedPrefix}"
            - CuratedBucket:
                Fn::ImportValue:
                  !Sub "${DatalakeStack}:CuratedBucketName"
      SchemaChangePolicy:
        UpdateBehavior: UPDATE_IN_DATABASE
        DeleteBehavior: DEPRECATE_IN_DATABASE


  OscETLJobRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
             Service: "glue.amazonaws.com"
            Action: "sts:AssumeRole"
      ManagedPolicyArns:
        - "arn:aws:iam::aws:policy/AmazonS3FullAccess"
        - "arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole"
        - !Ref AllowUseKmsKeyPolicy

  OscETLJob:
    Type: "AWS::Glue::Job"
    DependsOn: OscTable
    Properties:
      Role: !GetAtt OscETLJobRole.Arn
      Description:  "Transform to Parquet format"
      Command:
        Name: glueetl
        ScriptLocation: !Sub "s3://aws-glue-scripts-${AWS::AccountId}-${AWS::Region}/osc.py"
      DefaultArguments:
        --SOURCE_DATABASE: !Ref CuratedDatabaseName
        --SOURCE_TABLE: "osc/changes"
        --TARGET_DATABASE: !Ref StagingDatabaseName
        --TARGET_TABLE: "osc/changes"

  OscTable:
    Type: "AWS::Glue::Table"
    DependsOn: StagingDatabase
    Properties:
      CatalogId: !Ref AWS::AccountId
      DatabaseName: !Ref StagingDatabaseName
      TableInput:
        Name: 'osc/changes'
        TableType: EXTERNAL_TABLE
        Parameters:
          classification: parquet
        PartitionKeys:
          - Name: year
            Type: INT
          - Name: month
            Type: INT
          - Name: day
            Type: INT
          - Name: hour
            Type: INT
        StorageDescriptor:
          Columns:
            - Name: change
              Type: STRING
            - Name: feature
              Type: STRING
            - Name: id
              Type: BIGINT
            - Name: version
              Type: INT
            - Name: timestamp
              Type: STRING
            - Name: uid
              Type: INT
            - Name: user
              Type: STRING
            - Name: changeset
              Type: INT
            - Name: lon
              Type: DOUBLE
            - Name: lat
              Type: DOUBLE
          Location: !Sub
            - "s3://${StagingBucket}/osc/changes/"
            - StagingBucket:
                Fn::ImportValue:
                  !Sub "${DatalakeStack}:StagingBucketName"
          InputFormat: "org.apache.hadoop.hive.ql.io.parquet.MapredParquetInputFormat"
          OutputFormat: "org.apache.hadoop.hive.ql.io.parquet.MapredParquetOutputFormat"
          Compressed: true
          SerdeInfo:
            SerializationLibrary: "org.apache.hadoop.hive.ql.io.parquet.serde.ParquetHiveSerDe"
            Parameters:
              serialization.format: "1"
