AWSTemplateFormatVersion: '2010-09-09'
Description: OSC data ingestation
Transform: 'AWS::Serverless-2016-10-31'

Parameters:

  KmsKeyArn:
    Type: String
    Description: KMS key ARN to encrypt data on rest.

  DatalakeStack:
    Type: String
    Description: Datalake buckets stack name


Resources:

  IngestOscFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.6
      CodeUri: ./lambdas/ingest_osc/
      Timeout: 60
      MemorySize: 128
      Handler: ingest_osc.lambda_handler
      Policies:
        - S3CrudPolicy:
            BucketName:
              Fn::ImportValue:
                !Sub ${DatalakeStack}:VanillaBucketName
      Events:
        MinuteTimer:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)
            Input: |
              {
                "interval": "minute"
              }
      Environment:
        Variables:
          BUCKET_NAME:
            Fn::ImportValue:
              !Sub ${DatalakeStack}:VanillaBucketName

  ProcessOscFunction:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.6
      CodeUri: ./lambdas/process_osc/
      Timeout: 60
      MemorySize: 128
      Handler: process_osc.lambda_handler
      Policies:
        - S3ReadPolicy:
            BucketName:
              Fn::ImportValue:
                !Sub ${DatalakeStack}:VanillaBucketName
      Events:
        BucketObjectCreated:
          Type: SNS
          Properties:
            Topic:
              Fn::ImportValue:
                !Sub ${DatalakeStack}:VanillaObjectCreatedTopicArn
