AWSTemplateFormatVersion: "2010-09-09"

Description: Open street map change analysis (master template)

Parameters:

  KmsKeyArn:
    Default: ''
    Type: String
    Description: KMS key ARN to encrypt data on rest.

  S3IngestPrefix:
    Description: S3 prefix for OSC data ingested by Kinesis Firehose
      Stream.
    Type: String
    Default: Staging/osc_change/

  S3IngestBackupPrefix:
    Description: S3 prefix for OSC update data backup.
      Stream.
    Type: String
    Default: Vanilla/osc_change_backup/

  NodesOutputPrefix:
    Description: S3 prefix node output data
    Type: String
    Default: Staging/changed_nodes/

  ElasticSearchAccessLocation:
    AllowedPattern: (\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})/(\d{1,2})
    ConstraintDescription: must be a valid CIDR range of the form x.x.x.x/x.
    Default: 0.0.0.0/0
    Description: Limit access to public elastic search cluster to specified
      IP range
    MaxLength: '18'
    MinLength: '9'
    Type: String

Resources:

#  EncryptionKey:
#    Type: "AWS::KMS::Key"
##    DeletionPolicy: Retain
#    Properties:
#      Description: Encryption key for OSC change analysis data
#      KeyPolicy:
#        Version: "2012-10-17"
#        Id: Default
#        Statement:
#          - Sid: Enable IAM User Permissions
#            Effect: Allow
#            Principal:
#              AWS: !Join
#                - ''
#                - - 'arn:aws:iam::'
#                  - !Ref 'AWS::AccountId'
#                  - ':root'
#            Action: 'kms:*'
#            Resource: '*'

  StorageBucket:
    Type: "AWS::S3::Bucket"
#    DeletionPolicy: Retain
    Properties:
      LifecycleConfiguration:
        Rules:
          - Status: Enabled
            AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
            NoncurrentVersionTransitions:
              - StorageClass: STANDARD_IA
                TransitionInDays: 30
            NoncurrentVersionExpirationInDays: 90
            Transitions:
              - StorageClass: STANDARD_IA
                TransitionInDays: 360
#            ExpirationInDays: 720

  IngestStack:
    Type: "AWS::CloudFormation::Stack"
    Properties:
      TemplateURL: Ingest.template.yaml
      Parameters:
        KmsKeyArn: !Ref KmsKeyArn
        BucketArn:  !GetAtt StorageBucket.Arn
        S3IngestPrefix: !Ref S3IngestPrefix
        S3IngestBackupPrefix: !Ref S3IngestBackupPrefix

#  RealtimeStack:
#    Type: "AWS::CloudFormation::Stack"
#    Properties:
#      TemplateURL: Realtime.template.yaml
#      Parameters:
#        KmsKeyArn: !Ref KmsKeyArn
#        IngestStreamArn: !GetAtt IngestStack.Outputs.IngestStreamArn
#        BucketArn:  !GetAtt StorageBucket.Arn
#        NodesOutputPrefix: !Ref NodesOutputPrefix
#        ElasticSearchAccessLocation: !Ref ElasticSearchAccessLocation


#  BatchStack:
#    Type: "AWS::CloudFormation::Stack"
#    Properties:
#      TemplateURL: Batch.template.yaml


Outputs:
  DataLake:
    Description: S3 storage bucket
    Value: !Ref StorageBucket