Stack:
  TemplateBody:         ../solutions/CfnCD/SimpleCfnCd.template.yaml
  Region:               us-west-2
  StackName:            OSCAnalysis-CfnPipeline
  Capabilities:         [CAPABILITY_IAM]

  Tags:
    project:            OSCAnalysis
    enviornment:        production

  Parameters:
    CfnStackName:       OSCAnalysis
    CfnTemplate:        solutions/OSCAnalysis/OscAnalysis.template.yaml
    CfnStagCfg:         staging.json
    CfnProdCfg:         production.json
    CfnRepoName:        OSCAnalysisRepo
    CfnRepoDescription: OSM Change Analysis
    ApprovalEmails:     kotaimen_c@qq.com
    NumOfEmails:        1
    UseStaging:         "no"
    KmsKey:             "fe94ab5f-f381-4c3f-a6a0-83928c5e765d"
